Fixing gnomAD plots JSON structure
dashnowlab/STRchive pull request #128
Opened 2024-12-17 19:31 UTC by avvaruakshay

2024-12-17 19:42 UTC, vincerubinetti commented
There aren't really any frontend/site changes here, so my review isn't as useful.

However as a side note, I've noticed that these PRs have had lots of files without the EOF newline:
<img width="133" alt="Screenshot 2024-12-17 at 2 42 17 PM" src="https://github.com/user-attachments/assets/4e484705-2963-426c-bdf5-e7d25c8c3831" />

This isn't a big deal practically speaking, but I'd recommend everyone on the team get in the habit of adding this, and moreover, formatting your code with an opinionated formatter like Black for Python.

2024-12-17 20:06 UTC, hdashnow requested changes
This looks good on the preview. 
Could you please add the logic/list of reliable genes somewhere so we can have a record and update it as needed?

2024-12-17 21:17 UTC, avvaruakshay commented
I have added the reliability values to the code as a dictionary, for now. It can be updated as when the reliability status changes.

2024-12-18 12:39 UTC, hdashnow requested changes
There are 3 loci missing from the reliability dictionary. What did you all decide about these?

2024-12-18 12:39 UTC, hdashnow commented on scripts/gnomad-json.py
> +reliability = {
These loci are in the TSV data file but not in the reliability dictionary:
DMD
RILPL1
XYLT1

2024-12-18 22:41 UTC, hdashnow approved these changes

2024-12-18 22:42 UTC, merged