update with STR literature
dashnowlab/STRchive pull request #133
Opened 2024-12-20 00:29 UTC by laurelhiatt

updated here from recent lit

2024-12-20 16:51 UTC, hdashnow requested changes

2024-12-20 16:51 UTC, hdashnow commented on data/STRchive-loci.json
> +  "age_onset": "Typical: 20-49 [@pmid:11436124], Range: 8 [@pmid:15851746] - 83 [@doi:10.17161/2tmg0f25OMIM:601068].",
Should this be formatted like this?
`[@doi:https://doi.org/10.17161/2tmg0f25; @omim:601068]`

2024-12-20 16:51 UTC, hdashnow commented on data/STRchive-loci.json
> +  "details": "Overview of disease locus through 2024, including largest pathogenic allele of 4,000, described in Rimoldi et al review [@pmid:39643839]. Intermediate alleles (35-49) associated with pr
Was there supposed to be something after "Alleles" at the end?

2024-12-20 16:53 UTC, laurelhiatt commented
1.  no you don’t need the lead up to the DOI ID. 2. Ugh no the alleles bit was rewritten into the first sentence I added and evaded capture

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Harriet Dashnow ***@***.***>
Sent: Friday, December 20, 2024 9:51:34 AM
To: dashnowlab/STRchive ***@***.***>
Cc: laurelhiatt ***@***.***>; Author ***@***.***>
Subject: Re: [dashnowlab/STRchive] update with STR literature (PR #133)


@hdashnow requested changes on this pull request.

________________________________

In data/STRchive-loci.json<https://github.com/dashnowlab/STRchive/pull/133#discussion_r1894162670>:

> @@ -224,9 +224,9 @@
   "pathogenic_max": 68.0,
   "ref_copies": 34.0,
   "motif_len": 3,
-  "age_onset": "Typical: 20-49 ***@***.***:11436124], Range: 8 ***@***.***:15851746] - 78 ***@***.***:19227892].",
+  "age_onset": "Typical: 20-49 ***@***.***:11436124], Range: 8 ***@***.***:15851746] - 83 ***@***.***:10.17161/2tmg0f25OMIM:601068].",


Should this be formatted like this?
***@***.***:https://doi.org/10.17161/2tmg0f25; @omim:601068]

________________________________

In data/STRchive-loci.json<https://github.com/dashnowlab/STRchive/pull/133#discussion_r1894164453>:

> @@ -1513,7 +1513,7 @@
   "mechanism": "GoF",
   "mechanism_detail": "RNA gain-of-function: RNA gelation leading to misregulation of alternative splicing ***@***.***:36169768].",
   "source": [],
-  "details": "Intermediate alleles (35-49) associated with premutation ***@***.***:NBK1165]. 3%-8% of DM1 expansions contain variant repeats such as CCG and CGG, associated with later onset and milder phenotype ***@***.***:32851192]. In another study, interruptions of the CTG repeat with CCG, GGC, CTC or CAG motifs are estimated to occur in 3-11% of DM1 patients ***@***.***:35741732].",
+  "details": "Overview of disease locus through 2024, including largest pathogenic allele of 4,000, described in Rimoldi et al review ***@***.***:39643839]. Intermediate alleles (35-49) associated with premutation ***@***.***:NBK1165]. 3%-8% of DM1 expansions contain variant repeats such as CCG and CGG, associated with later onset and milder phenotype ***@***.***:32851192]. In another study, interruptions of the CTG repeat with CCG, GGC, CTC or CAG motifs are estimated to occur in 3-11% of DM1 patients ***@***.***:35741732]. Alleles",


Was there supposed to be something after "Alleles" at the end?

—
Reply to this email directly, view it on GitHub<https://github.com/dashnowlab/STRchive/pull/133#pullrequestreview-2517945675>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AULUPMCV2IV4ENH54BCHQBT2GRDJNAVCNFSM6AAAAABT6CSWKSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMJXHE2DKNRXGU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-12-24 18:53 UTC, hdashnow approved these changes

2024-12-30 16:34 UTC, merged