new locus
dashnowlab/STRchive pull request #48
Opened 2024-10-25 21:18 UTC by laurelhiatt

RAI1. for some reason it didn't pull the latest columns on my local desktop (grrr), but I have the orphanet, GARD, and WebSTR_hg38, plus the disease description. would it be easier for you to add the pull request from this and edit, or should I add them on my end?  what say ye

2024-10-25 22:05 UTC, laurelhiatt commented
MedGen":null

     "Orphanet":”86814”

     "GARD":”16758”

     "WebSTR_hg38":"486849”

     "WebSTR_hg19":null

     "TR-gnomAD":null

     "disease_description":”Cortical tremor, seizures with generalised motor (tonic-clonic) onset (PMID: 38876750)”



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Harriet Dashnow ***@***.***>
Sent: Friday, October 25, 2024 3:48:14 PM
To: dashnowlab/STRchive ***@***.***>
Cc: laurelhiatt ***@***.***>; Author ***@***.***>
Subject: Re: [dashnowlab/STRchive] new locus: RAI1 (PR #48)


If you want to put the orphanet, GARD, and WebSTR_hg38, plus the disease description in this thread I can always edit the branch to add them

—
Reply to this email directly, view it on GitHub<https://github.com/dashnowlab/STRchive/pull/48#issuecomment-2438927064>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AULUPMBHNDYOSGRBKJLVTNTZ5K4B5AVCNFSM6AAAAABQUBSOHGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMZYHEZDOMBWGQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-10-28 22:52 UTC, hdashnow requested changes

2024-10-28 22:52 UTC, hdashnow commented on data/STRchive-database.json
> +        "pathogenic_motif_reference_orientation":"TTTCA",
ref and gene orientation pathogenic motifs aren't reverse complements of each other

2024-10-28 22:52 UTC, hdashnow commented on data/STRchive-database.json
> +        "normal":"16\u201322",
Some sort of code thing going on here?

2024-10-28 22:52 UTC, hdashnow commented on data/STRchive-database.json
> +        "details":"Seen in one large family from Mali . The pathogenic expanded repeats observed were estimated to be (TTTTA)278-715(TTTCA)9\u2013334 (PMID: 37994247)",
More funky formatting. Probably a special character conversion thing

2024-10-28 22:52 UTC, hdashnow commented on data/STRchive-database.json
> +        "pathogenic_motif_reference_orientation":"TTTCA",
I think this should be:
```
        "reference_motif_reference_orientation":"TTTTA",
        "pathogenic_motif_reference_orientation":"TTTCA",
        "pathogenic_motif_gene_orientation":"TTTCA",
        "benign_motif_reference_orientation":"TTTTA",
        "benign_motif_gene_orientation":"TTTTA",
        "unknown_motif_reference_orientation":"GGGGT,GGGAT",
        "unknown_motif_gene_orientation":"GGGGT,GGGAT",
```

some TTTTA-only expansions were found in controls. So I'm not entirely sure if it should be listed as benign, unknown or pathogenic! Thoughts?

There was also a 
![image](https://github.com/user-attachments/assets/a440cdd5-c9f5-4007-a01f-3e5b10505f2d)

And it appears TTTTA was also expanded in the affected individuals. But 

<img width="797" alt="Screenshot 2024-10-25 at 4 05 29 PM" src="https://github.com/user-attachments/assets/46aa007a-a31b-48e2-bb6c-5f2cbfd9b7f5">

2024-10-28 22:52 UTC, hdashnow commented on data/STRchive-database.json
> +        "pathogenic":"9-334",
Based on this paper alone, seems like they are suggesting 14+ pathogenic, but since no TTTCA were observed in controls, maybe 9 is also reasonable.

> In one of two reads of III-14, only nine TTTCA repeat units were detected. This is the smallest number ever reported; the previously reported shortest repeat unit was 14.[24](https://movementdisorders.onlinelibrary.wiley.com/doi/10.1002/mds.29654#mds29654-bib-0024) TTTCA repeat units of another read numbered 46. Whether the insertion of nine TTTCA repeat units is pathogenic requires further investigation.

https://movementdisorders.onlinelibrary.wiley.com/doi/10.1002/mds.29654

2024-10-28 22:52 UTC, hdashnow commented on data/STRchive-database.json
> +        "details":"Seen in one large family from Mali . The pathogenic expanded repeats observed were estimated to be (TTTTA)278-715(TTTCA)9\u2013334 (PMID: 37994247)",
Maybe could add:
A single individual was observed with an allele with additional interruptions: (TTTTA)exp(GGGGT)ins(GGGAT)ins(TTTCA)ins

Here's the full allele. It's a bit more complicated than they suggest

> TATTTTATTTTATTATTTTATTATTTTATTTTATTTTATTATTTTATTATTATTTTATTATTTTATTTTATTATTATTTTATTTTATATTTTATTTTATTATTATTATTATTATTATTATTATTATTATTATTATTATTATTATTATTATTTTATTTATTATTTTATTATTATTATTATTATTATTATTATTATTATTATTATTATTATTATTTTATTTTATTATTTTATTTTATTTTATTTATTATTTTATTATTATTATTATTATTATTATTATTATTATTATTTTATTTTATTTTATTΠATTTTATTTTATTATTATTATTATTATTATTATTATTATTATTATTATTATTATTATTATTTTATTTTATTTTATTATTATTATTATTATTATTATTATTATTATTATTATTATTATTATTATTTTATTTTATTTTATTTTTATTTTATTTTATTATTATTATTTTATTATTATTTTATTATTTTATTTTATTATTATTTTATTATTTTATTTTATTTTATTATTTTATTTTATTTTTTTTTTTTTTTTATTTTATTTTATTTTATTTTATTTTATTTTTTTTTTTTATTTATTTTTTTTTTTTTTTTTTTTTATTTTATTTTATTTTATTTTATTTTATTTTTTTTTTTTTTTTTGTTTGTTTTATGTTGTTTGTTGTGTTTTTTGTTTTTTTTTTTTTTTTTTTGTTTTATTTTATTTTTTGTTATTTTTTTTTTTTTTTTATGTTTTATGTTGTTTGTTTTTTTTTTTTTTTTGTGTTTGGTGGGTTGGTGTTGGGTGTTGGTGTGGGGTGGGTTGTTTGTTTTTGTTTTTTTTTTTTTTTTTGTTTTTTTTTATTGTTTTGGTTGTGTTTTTTTTGTTGTGTTGTGGTTGTTTGTGGTTTGGGTGGGGTGGGGTGGGTGGGTGGGTGGGTGGGTGGGGTGGGGTGGGGTGGGTGGTGGGTTGTTGGTTGGGGTGGGTGTGGGTGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGTGGGTGGGGTGGGGTGGGTGGGGTGGGGTGGGGTGGGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGTGGGGTGGGGTGGGTGGGTGGGTGGGGTGGGGTGGGGTGGGTGGGGTGGGGTGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGTGGGGTGGGTGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGGTGGGTGGGGTGGGTGGGTGGGGTGGGGTGGGGTGGGTGGGGTGGGGTGGGGTGGGTGGGTGGGGTGGGGTGGGTGGGGTGGGTGGTGGGGTGGGGTGGGGTGGGGTTGTGTTGTTTTGTTTGTTTTGTTTGTATTTATTTTATTTTGTTTGATGGGATGTGATGGGATGGGATGGGATGGGATTTATGTATGTTGATTGTATGTATGGATTGTATGGATGGGATGATGTGATGGGATGGGATGGGATGGGATTGGATGGATGGATGGGATGGGATGGATGATGGATTGATATTTTATTTAATTTATTTATGTGATGGGATGGGATGGGATGGGATGGATTGATGTATGATTTTTTTTATTTATGTATGTGATTGATGTATGGATTGATGGGATGGATGGGATGGGATGGGATGGATGGGATGGGATGGGATGGGATGGGATGGATGGGATGGGATGGTGGGATGGATGGGATGGGATGGATGGGATGGGATGGATGGGATGGGATGGATGGATGGATGGATGTGGATGGGATGGGATGGGATTAATTTCATTTATTTCATTTCATTTATTTCATTTATTTAATTTATGTATTTAATTATTAATTTCATTTCATTATTCATTAATTTCATTTCATTTCATTTCATTTAATTTCATTTCATTTCATTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTATTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTCATTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTCATCATTTCATTTCATTTCATTTCATTTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCATTTCA

2024-10-28 22:52 UTC, hdashnow commented on data/STRchive-database.json
> +        "normal_max":22.0,
This size range refers to the benign motif, not the pathogenic one. Could be confusing. Should be 0?

> None of the 208 controls had this pentanucleotide repeat expansion. The distribution of the number of TTTTA repeat units among all 208 controls ranges between 16 and 22 repeat units

2024-10-30 16:29 UTC, hdashnow commented
@laurelhiatt I did an update based on our discussion. Could you please take a look when you get a chance and let me know if you agree with the changes?

2024-10-30 23:13 UTC, hdashnow commented
I'm going to merge this with the benign min/max set to null for now until we can think about how best to represent the complexity. Full information is in the details field.

2024-10-30 23:13 UTC, merged